### ISSUE TITLE
크래시가 나는 것 같습니다.

### ISSUE THREAD

**Issue by Kinaress1** [enddl3788/BackpackHero_Korean#5]
오늘 올려주신 버전 이전에는 잘 구동되었습니다만,

새 버전 압축파일을 적용 시 첨부와 같은 화면에서 구동이 되지 않는 것을 확인했습니다.

버튼은 눌리는지 제일 아래 버튼을 누르니 종료되긴 합니다.

![125214](https://github.com/enddl3788/BackpackHero_Korean/assets/151472037/abaccc12-557d-43f8-b88f-41c9388f0e43)

압축 해제는 최신버전 반디집을 사용중입니다.

고생 많으십니다. 감사합니다.

**Comment by Kinaress1** [comment]
추가) 게임 종료 말고 다른 버튼은 눌러도 아무 동작을 하지 않는 것 같습니다

**Comment by Kinaress1** [comment]
깃헙은 처음이라 실수가 있었습니다. ㅠ

sharedassets0.assets 파일만 빼고 덮어씌울 경우엔 동작은 됩니다만, 글자가 깨지는 현상은 그대로인 것 같습니다.

감사합니다!

**Comment by enddl3788** [comment]
확인 했습니다! 저가 올린 파일에서는 문제가 없었지만, 대용량 파일을 올릴 때 LFS를 사용하여 업로드 하지만 그 과정에서 문제가 있는 것 같습니다.

sharedassets0.assets에 나눔고딕 폰트 파일이 있어서, 용량이 195,972KB이여야 하는데,
깃허브를 통해 다운을 받으니 1KB로 비어 있네요!

해결되면 다시 comment 달아드릴께요!

**Comment by enddl3788** [comment]
단순히 다운받을 repository에서 [Code] - [Download ZIP]으로 받으면 될 줄 알았는데 아니였네요!

먼저 해결방법으로는 아래 링크에서 수동으로 다운 받아서 교체하는 방법이 있습니다.
https://github.com/enddl3788/BackpackHero_Korean/blob/ec674d840c5362e71f24c8ee0d78267c9683cc9b/Backpack%20Hero_Data/sharedassets0.assets
![화면 캡처 2023-11-20 170007](https://github.com/enddl3788/BackpackHero_Korean/assets/75508349/09c8f145-2e2b-4ee0-a694-88714af652d5)

LFS를 통한 공유가 아닌 다른 방법을 찾아보도록 하겠습니다!

**Comment by enddl3788** [comment]
패치 적용 방법을 변경했습니다! 
기존 다운로드 방식을 깃허브가 아닌 구글 드라이브로 이동하여 문제점을 해결했습니다. 
기여해주셔서 감사합니다! 해결되셨다면 이슈를 닫아주세요.

**Comment by Kinaress1** [comment]
테스트 결과 시청빼고 아주 잘 됩니다 감사합니다! 덕분에 완벽하게 하고 있습니다
